version: '3.8'

services:
  app:
    build:
      context: .
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16
    volumes:
      - ..:/workspace:cached
      - bde-isima-node_modules:/workspace/node_modules
      - bde-isima-vs-code-extensions:/home/node/.vscode-server/extensions
      - bde-isima-bashhistory:/commandhistory
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - 3000:3000

    networks:
      - bde-isima

  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    ports:
      - 5432:5432

    networks:
      - bde-isima

volumes:
  bde-isima-node_modules:
  bde-isima-vs-code-extensions:
  bde-isima-bashhistory:

networks:
  bde-isima:
    external: false
